import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  FolderIcon,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LogIn,
  LucideIcon,
  MessagesSquare,
  ActivityIcon,
  Moon,
  MoreVertical,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User2Icon,
  Users,
  X,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  folder: FolderIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  activity: ActivityIcon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  users: Users,
  arrowRight: ArrowRight,
  help: HelpCircle,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  topic: MessagesSquare,
  check: Check,
};
